# Generated by Django 3.0.4 on 2020-03-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke_catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.TextField()),
                ('Writter', models.CharField(max_length=200)),
                ('joke_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joke_site.Joke_catagory')),
            ],
        ),
    ]
