# Generated by Django 3.0.4 on 2020-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='joke_title',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
